name: Release & Publish to NPM
on:
  workflow_dispatch:
jobs:
  release:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    name: Release & Publish to NPM
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: '.npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build:package
      - name: Release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
